#  ___ ___ _  _
# | _ ) __| \| | Brian E Nguyen
# | _ \ _|| .` | brianenguyen.com
# |___/___|_|\_| github.com/brianenguyen/

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 0.7
title           = "Alacritty"

[window.padding]
x = 12
y = 12

# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
